--!strict
--!native
--!optimize 2
return {
    now = function()
        error("Not implemented");
    end,
    fromUnixTimestamp = function()
        error("Not implemented");
    end,
    fromUnixTimestampMillis = function()
        error("Not implemented");
    end,
    fromUniversalTime = function()
        error("Not implemented");
    end,
    fromLocalTime = function()
        error("Not implemented");
    end,
    fromIsoDate = function()
        error("Not implemented");
    end,
};
